### ISSUE TITLE
Ask for the selected scenes used in the paper

### ISSUE THREAD

**Issue by ucwxb** [xhd0612/GaussianRoom#11]
Thanks for your excellent work!
Could you please specify which scenes from ScanNet v2 and ScanNet++ were used in the experiment section of your paper? This information would greatly assist me in my research.
Thank you!

**Comment by xhd0612** [comment]
Hi!
The 8 ScanNet scenes we are using are: `scene0050_00`, `scene0085_00`, `scene0114_02`, `scene0580_00`, `scene0603_00`, `scene0616_00`, `scene00617_00`, and `scene0721_00`. The 2 ScanNet++ scenes we are using are `8b5caf3398` and `8d563fc2cc`.

**Comment by ucwxb** [comment]
Thanks a lot!
