### ISSUE TITLE
how can we get the GT mesh 

### ISSUE THREAD

**Issue by 00Haocheng** [xhd0612/GaussianRoom#4]
Hello, to my knowledge, the grid in the scannet dataset is incomplete, which will affect the reconstruction evaluation. I  wonder how to obtain the true value of the room model when evaluating reconstruction metrics?

**Comment by xhd0612** [comment]
Hello, we use the ground truth mesh in the ScanNet dataset.To ensure a fair evaluation, we clean the generated mesh before comparing it with the ground truth. The authors of  [NeuRIS](https://github.com/jiepengwang/NeuRIS/tree/main) kindly provide the evaluation method, which can be used as a reference.

**Comment by 00Haocheng** [comment]
I see. Thank you very much for your reply!
